### ISSUE TITLE
Strange CloudFront behavior

### ISSUE THREAD

**Issue by ryanblock** [architect/aws-lite#77]
### Describe the issue

When making subsequent CloudFront requests, I see very strange behavior that I can't easily trace to aws-lite. Here are two scenarios outlined:
- Creating creating two distributions back to back
- Creating a new distribution after invalidating another distribution

### Expected behavior

I expect to be able to run any number of valid CloudFront requests serially, so long as they are not causing rate limiting issues (see https://docs.aws.amazon.com/cloudfront/latest/APIReference/CommonErrors.html error `400`).

## Creating creating two distributions back to back

Repro steps:
- Call `Cloudfront.CreateDistribution()` with a valid distribution configuration
- Call it a second time immediately after with a separate, but also valid distribution configuration
- Usually this produces a 408 error as below:

```
[aws-lite] Request: {
  time: '2024-01-22T19:09:06.756Z',
  service: 'cloudfront',
  method: 'POST',
  url: 'https://cloudfront.amazonaws.com/2020-05-31/distribution',
  headers: {
    'content-type': 'application/xml',
    Host: 'cloudfront.amazonaws.com',
    'Content-Length': 2437,
    'X-Amz-Date': '20240122T190905Z',
    Authorization: 'AWS4-HMAC-SHA256 Credential=AKIAIAE...'
  },
  body: '...'
} 

[aws-lite] Response: {
  time: '2024-01-22T19:11:16.920Z',
  statusCode: 408,
  headers: {
    'content-length': '0',
    date: 'Mon, 22 Jan 2024 19:10:11 GMT',
    connection: 'close'
  },
  body: '<no body>'
} 

Error: @aws-lite/client: CloudFront.CreateDistribution: unknown error
    at errorHandler (/project-path/node_modules/@aws-lite/client/src/error.js:13:46)
    at Object.CreateDistribution (/project-path/node_modules/@aws-lite/client/src/client-factory.js:207:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 408,
  headers: {
    'content-length': '0',
    date: 'Mon, 22 Jan 2024 19:10:11 GMT',
    connection: 'close'
  },
  service: 'cloudfront',
  property: 'CloudFront',
  awsDoc: 'https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateDistribution.html',
  readme: 'https://aws-lite.org/services/cloudfront#createdistribution'
}
```

Other times, we'll just a raw HTTP error:

```
[aws-lite] Request: {
  time: '2024-01-22T19:18:15.109Z',
  service: 'cloudfront',
  method: 'POST',
  url: 'https://cloudfront.amazonaws.com/2020-05-31/distribution',
  headers: {
    'content-type': 'application/xml',
    Host: 'cloudfront.amazonaws.com',
    'Content-Length': 2437,
    'X-Amz-Date': '20240122T191744Z',
    Authorization: 'AWS4-HMAC-SHA256 Credential=AKIAIAE...'
  },
  body: '...'
} 

[aws-lite] HTTP error: Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: @aws-lite/client: CloudFront.CreateDistribution: read ECONNRESET
    at errorHandler (/project-path/node_modules/@aws-lite/client/src/error.js:13:46)
    at Object.CreateDistribution (/project-path/node_modules/@aws-lite/client/src/client-factory.js:207:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  service: 'cloudfront',
  property: 'CloudFront',
  awsDoc: 'https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateDistribution.html',
  readme: 'https://aws-lite.org/services/cloudfront#createdistribution',
  rawStack: 'Error: read ECONNRESET\n' +
    '    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)',
  host: 'cloudfront.amazonaws.com',
  protocol: 'https'
}
```

When spaced out enough, this does not appear to be an issue.

## Creating a new distribution after invalidating another distribution

Repro steps:
- Call `Cloudfront.CreateInvalidation()` with a valid invalidation payload
- Call `Cloudfront.CreateDistribution()` with a valid distribution configuration right after
- This produces a signature error(!?) as below:

```
@aws-lite/client: CloudFront.CreateDistribution: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
    at errorHandler (/project-path/node_modules/@aws-lite/client/src/error.js:13:46)
    at Object.CreateDistribution (/project-path/node_modules/@aws-lite/client/src/client-factory.js:207:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 403,
  headers: {
    'x-amzn-requestid': 'fa2230ee-e308-4f43-880e-64e47d74dfeb',
    'content-type': 'text/xml',
    'content-length': '433',
    date: 'Mon, 22 Jan 2024 19:47:29 GMT'
  },
  Type: 'Sender',
  code: 'SignatureDoesNotMatch',
  service: 'cloudfront',
  property: 'CloudFront',
  awsDoc: 'https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateDistribution.html',
  readme: 'https://aws-lite.org/services/cloudfront#createdistribution'
}
```

This does not occur when `CreateDistribution` is called without calling `CreateInvalidation` prior; similarly, calling `CreateInvalidation` multiple times in a row does not present this issue.

### Platform / version

- OS + version: macOS 14.2.1
- Node version: Node.js 20.10
- aws-lite version: 0.14.1
- CloudFront plugin version: 0.0.6

### How urgent do you feel this bug is?

P3

**Comment by ryanblock** [comment]
I can confirm this is no longer happening, and reading over these notes, these symptoms sound exactly like the `aws4` header reference mutation issue patched earlier this week (see [here](https://github.com/architect/aws-lite/commit/42c1bab29f134fe36d100c92dd0bd9bcaf72a2b2) and [here](https://github.com/mhart/aws4/issues/164)).
